### PR TITLE
Add owner, logGroup and logStream to es_event in _handle_kinesis_record when using expand_event_list_from_field 

### PR DESCRIPTION
**Pull request by expertalex**
## What does this PR do?
Add owner, logGroup and logStream to es_event in _handle_kinesis_record when using expand_event_list_from_field 
image

Get the full event as a string and transform it to JSON 
Save necessary fields in variables
image

Set variables to es_event
image

When Using expand_event_list_from_field  some data gets lost
See Issue: https://github.com/elastic/elastic-serverless-forwarder/issues/162 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.md`

## Related issues

-

### CODE REVIEW

**Comment by aspacca** [comment]
hi @expertalex , thanks for the contribution, but the solution is too generic: kinesis stream does not necessarily are aggregation of cloud watch logs.

I know I haven't given feedback to https://github.com/elastic/elastic-serverless-forwarder/issues/162 because I'm still thinking about the most viable solution.

one possibility I'm thinking about is to introduce `add_root_fields_to_event_list_extracted_from_field`. I think the name should be self explanatory, in case you have any doubt please let me know

**Comment by aspacca** [comment]
hello @expertalex , closing this PR for now.

stay tuned for the feature you need

**Comment by expertalex** [comment]
Hello @aspacca can you inform me about the status of this feature? 
Are someone working on it or I can implement your suggestion:
"one possibility I'm thinking about is to introduce add_root_fields_to_event_list_extracted_from_field. I think the name should be self explanatory, in case you have any doubt please let me know"

**Comment by aspacca** [comment]
hi @expertalex , we want to add the `add_root_fields_to_event_list_extracted_from_field` feature, but it's not planned internally at the moment

feel free to open a PR for it if you have time, we'll give priority to the review

thanks

**Pull request closed without merging**
