### PR TITLE
Cache describe_regions using lru_cache from stdlib

### PR DESCRIPTION
**Pull request by zmoog**
## What does this PR do?

Caches EC2:DescribeRegion API calls response.

## Why is it important?

On high-volume deployments, ESF can hit the EC2:DescribeRegions API requests limit, causing throttling errors like the following:

```text
An error occurred (RequestLimitExceeded) when calling the DescribeRegions operation (reached max retries: 4): Request limit exceeded.
```

ESF needs the list of existing regions to parse incoming events from the `cloudwatch-logs` input. Since new AWS region additions do not happen frequently, picking up and caching the list of existing regions at function startup seems adequate.

The list of existing AWS regions is available at https://aws.amazon.com/about-aws/global-infrastructure/regions_az/

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.md`

### CODE REVIEW

**Comment by zmoog** [comment]
I can probably add cache expiration to avoid a stale region list:

```python
import time
from functools import wraps
from typing import Any, Callable

def cache_for(seconds: int) -> Callable:
    def decorator(func: Callable) -> Callable:
        cache = {}
        stats = {'hits': 0, 'misses': 0}
        
        @wraps(func)
        def wrapper(*args, **kwargs) -> Any:
            current_time = time.time()
            if 'result' in cache and (current_time - cache['time'] < seconds):
                stats['hits'] += 1
                return cache['result']
            result = func(*args, **kwargs)
            cache['result'] = result
            cache['time'] = current_time
            stats['misses'] += 1
            return result
        
        wrapper.cache_stats = stats
        return wrapper
    return decorator

@cache_for(seconds=60)
def describe_regions(all_regions: bool = True) -> Any:
    """
    Fetches all regions from AWS and returns the response.

    :return: The response from the describe_regions method
    """
    return get_ec2_client().describe_regions(AllRegions=all_regions)

# Example usage with AWS regions
import boto3

def get_ec2_client():
    return boto3.client('ec2')

# Example usage to access cache statistics
if __name__ == "__main__":
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 0, 'misses': 1}

    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 1, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 2, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 3, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 4, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 5, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 6, 'misses': 1}
    describe_regions()
    print(describe_regions.cache_stats)  # {'hits': 7, 'misses': 1}
```

I get the following output:

```
{'hits': 0, 'misses': 1}
{'hits': 1, 'misses': 1}
{'hits': 2, 'misses': 1}
{'hits': 3, 'misses': 1}
{'hits': 4, 'misses': 1}
{'hits': 5, 'misses': 1}
{'hits': 6, 'misses': 1}
{'hits': 7, 'misses': 1}
```

**Comment by zmoog** [comment]
Or, we can use a 3rd party library like https://cachetools.readthedocs.io/en/latest/

```python
from typing import Any

from cachetools.func import ttl_cache


@ttl_cache(ttl=1800) # 30 minutes
def describe_regions(all_regions: bool = True) -> Any:
    """
    Fetches all regions from AWS and returns the response.

    :return: The response from the describe_regions method
    """
    print("Fetching regions from AWS...")
    return get_ec2_client().describe_regions(AllRegions=all_regions)

# Example usage with AWS regions
import boto3

def get_ec2_client():
    return boto3.client('ec2')

# Example usage to access cache statistics
if __name__ == "__main__":
    
    # print(dir(describe_regions))

    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 0, 'misses': 1}

    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 1, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 2, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 3, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 4, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 5, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 6, 'misses': 1}
    describe_regions(all_regions=False)
    print(describe_regions.cache_info())  # {'hits': 7, 'misses': 1}
```

**Comment by zmoog** [comment]
Thanks for the in-depth analysis.

I tested the cloudwatch lambda trigger on the AWS console and ESF. As of today, it seems cloudwatch lambda triggers can only work with log groups in the same region from as the lambda functions. For example, if I deploy ESF on `eu-west-1`, I can only process log events on log groups on `eu-west-1`.

Given this limit, there is no reason to keep calling the EC2:DescribeRegion API on every event.

I plan to remove this API call from ESF.

Here's my plan:

- Add the `@lru_cache` decorator from the standard library to reduce the number of API calls from one every event to just one on start. This is a small risk change that would allow to ship a patch release today.
- Go through the process of removing the API call (change the code to use the region from the function, remove the required permissions from the infrastructure, and test the whole package).

WDYT?

**Comment by constanca-m** [comment]
I am fine with approving the PR as it is. 

You need to change the version of ESF currently (I believe you need to update the changelog and [version.py](https://github.com/elastic/elastic-serverless-forwarder/blob/main/share/version.py). After that the release workflow will be triggered, but if we push this change just like this, then nothing will happen.

**Comment by zmoog** [comment]
> You need to change the version of ESF currently (I believe you need to update the changelog and [version.py](https://github.com/elastic/elastic-serverless-forwarder/blob/main/share/version.py). After that the release workflow will be triggered, but if we push this change just like this, then nothing will happen.

Thanks! On it.

**Review by constanca-m — APPROVED** [review]
Thanks @zmoog ! I would say we should keep https://github.com/elastic/elastic-serverless-forwarder/issues/723 open. I have copied and pasted my comment above so we know where we stand now.

I doubt we will have issues like this again with the cache, but let's see!

**Comment by zmoog** [comment]
> I would say we should keep #723 open. 

I agree!

> I doubt we will have issues like this again with the cache, but let's see!

I'll work on removing the EC2:DescribeRegions API call later this week.

**Pull request merged**
