### PR TITLE
Direct sqs input

### PR DESCRIPTION
**Pull request by aspacca**
Enhancement

## What does this PR do?
Adds support for direct SQS input

## Why is it important?
In preparation of cloudwatch logs inputs, in case it needs to rely on the  continuing queue, a direct sqs input is needed

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.md`

## Author's Checklist

- [ ]

## Related issues

-
Relats #52

### CODE REVIEW

**Comment by aspacca** [comment]
@v1v integration tests using docker library to starts container started failing in this PR (https://beats-ci.elastic.co/job/Library/job/elastic-serverless-forwarder-mbp/job/PR-91/3/consoleFull)

the tests run in a docker container with docker running inside, any changes in the workers or anything else that can affect the outcome?

I cannot reproduce locally

**Comment by v1v** [comment]
> @v1v integration tests using docker library to starts container started failing in this PR

Do you mean that failures started just in this PR? I see build failures in the `main` branch: 
- https://beats-ci.elastic.co/job/Library/job/elastic-serverless-forwarder-mbp/job/main/buildTimeTrend

Are those failures related to the same issue? Just wanna be sure if the failure is caused by a particular change in the project or in the infrastructure

> the tests run in a docker container with docker running inside, any changes in the workers or anything else that can affect the outcome?

As far as I know, linux VMs are configured with docker, so we use docker extensively in some other projects, though I don't know if DinD could be problematic and what version might be needed.

If your local development differs from the one in the CI, you can either spin up a VM to access to and debug what's going on, or connect to an existing VM while the build runs, let me know if you need those details and I can send you the links.

**Comment by aspacca** [comment]
> Do you mean that failures started just in this PR? I see build failures in the `main` branch:

yes, I experience in this PR since it was the only one I had since last week.
The failures in the `main` branch since build 45 are the same failures of this PR

I will connect to the worker node to debug, just wondering if there was any change around 45 build time

**Review by endorama — APPROVED** [review]

**Comment by v1v** [comment]
> I will connect to the worker node to debug, just wondering if there was any change around 45 build time

You might need to contact the `ci-systems` team as they own the CI platform and might have a clear understanding of what's the state for the CI workers in terms of what pieces of software have been installed.

**Comment by aspacca** [comment]
@v1v 

this fixed the tests: https://github.com/elastic/elastic-serverless-forwarder/pull/91/commits/d9b1ece0d10240cba2be78769b5dffa6b3040b5f

I figured that from the log in CI:
```
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/create: Internal Server Error ("error creating aufs mount to /var/lib/docker/aufs/mnt/cf02518bfe61a7a58a8109fdf0d1908669eb92577d82bd7c4e74942b62ae3d35-init: mount 
```

do you have any hint about why it was working without the fix before? thanks

**Pull request merged**
