### PR TITLE
replace ping with health and wait_for_status green

### LINKED ISSUE #27: Unstable tests
Hello,

It looks like there are a few unstable tests in the new pipeline for this project:

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/4/testReport/junit/tests.storage.test_s3/TestS3Storage/test_get_by_lines/

and

https://beats-ci.elastic.co/view/All/job/Library/job/elastic-serverless-forwarder-mbp/job/main/5/testReport/junit/tests.handlers.aws.test_handler/TestLambdaHandlerSuccess/test_lambda_handler/

We're now monitoring the health of this pipeline so if these could be cleaned up, it would be terrific. Thanks!

### PR DESCRIPTION
**Pull request by aspacca**
Fixes #27

### CODE REVIEW

**Comment by aspacca** [comment]
@cachedout seems stable now

**Comment by aspacca** [comment]
last failure unrelated
```
[2021-11-11T14:40:10.716Z] >               assert gzip_full[-1][1] == MockContent.f_size_plain
[2021-11-11T14:40:10.716Z] E               IndexError: list index out of range
```

I have to investigate on this

@cachedout if you are fine I'd say instability due to elasticsearch is fixed

**Review by cachedout — APPROVED** [review]
Looks great. Thanks @aspacca !

**Pull request merged**
